[tasks.install]
description = "install all dependencies"
run = "echo TODO: install goes here"

[tasks.check]
description = "check all dependencies"
depends = ["install", "pre-check-env"]
run = "echo TODO: check goes here"

[tasks.build]
description = "build all the things"
depends = ["check"]
run = "echo TODO: build goes here"

[tasks.clean]
description = "clean up"
run = "echo TODO: clean goes here"

[tools]
node = "22.18.0"
